name: Build tgvisd

on:
  push:
    paths:
      - 'greentea/mysql/**'
      - 'greentea/td/**'
      - 'greentea/tgvisd/**'
  pull_request:
    paths:
      - 'greentea/mysql/**'
      - 'greentea/td/**'
      - 'greentea/tgvisd/**'

jobs:
  build-tgvisd:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    env:
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Display software versions
      run: |
        ${{matrix.cc}} --version;
        ${{matrix.cxx}} --version;

    - name: Install dependencies
      run: |
        sudo apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake clang libc++-dev libc++abi-dev;

    - name: Build tdlib
      run: |
        cd greentea;
        git submodule init;
        git submodule update;
        cd td;
        rm -rf build;
        mkdir -pv build;
        cd build;
        VERBOSE=1 CC=${{matrix.cc}} CXX=${{matrix.cxx}} cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../build/tdlib ..;
        VERBOSE=1 cmake --build . -j$(nproc);
        VERBOSE=1 cmake --build . --target install -j$(nproc);
        cd ../../..;

    - name: Build tgvisd
      run: |
        cd greentea;
        mkdir -pv build;
        cd build;
        mkdir -pv tgvisd;
        cd tgvisd;
        VERBOSE=1 CC=${{matrix.cc}} CXX=${{matrix.cxx}} cmake -DCMAKE_BUILD_TYPE=Release ../../tgvisd;
        VERBOSE=1 cmake --build . -j$(nproc);
